encrypt using new key endpoint
this updates `cape encrypt` to use `/v1/users/<username>/key` to get the
rsa key for encryption. We were previously getting a key directly from
the enclave using a function token. This brings it up to parity with the
js sdk

Usage looks like so:

```
$ cape encrypt hello --username fjsdklfjkladsfjklsdjfklsad
Error: user not found
```

```
$ cape encrypt hello
cape:Lm7374BX64zouE+2VasPcW5yCVWSSF4DaSIfdWVI0kcHAnsXKn12nE3r5sX0Dz9fKOIL7lHMYOMjCzHfroD6t2U42EK7vxBdRkIyewgwYOHogP4Lf0N0DbHHg9BBIsa7HUD6oLgnAIRPFK1QS+jV+GlADfnRGNw2s4RHj7UH47hnj14Ra0J5TkxXvLj8Gb4dZtX3KZzgvnchsTZIcAd47RQVcqC/LKXjb41b2r7o0aEog/f2vG0icrfuECxrKnRzaSg3Lbb0FvYS6dcEiVVgqXJX3Zhb/n59gIheK4GYhWm1XF+Fr8kgoXtOVIVNtzQNZdYPX7HyRbyLMfsInA1z7IDMQ6w/nMDuANakwrYM+w9KCFs4gNHCPG8lOHeJNPNQ3SnRyHRiSD965JSZ8qo8FRtEfv4f5DFnyNirazkUolkZV58cUVmIWRrQSUCoQzx90j6QnFx0C1Iz+lsf1UsIBTdJJra9BP6AsckvQ/uBCjKkyCLC/Jxpf16NEph2KjxuSeurxZ32EJDgk18xuakOtX4dbRF3p2YY4EJEo/7nzfmCTZUJ6JhAoITrNXIq+0k4pBTZL9pc+g/6xKh9qnU3R/59WJsfp/Tv6iw1vfiSZvhN/q2EYOi3iWzdyStbrczZ4uM60gn/Ywq3WH/pG4JNybQCWK1/lcs5PE2OxFsKRxgDDPHismc7/iq1avgu6Ympsr9CqX7dp3sGaKbxAHBNofA=
```

```
$ cape encrypt hello --username gavinuhma
cape:zumK8SdRB0HjPofH1bIVXkoMmAb39EZ/1riH1pRex/66B4K3BpkmYsH1ODq1SK1i3T36iycItFyBc4NMKgwoku5cjq4WTOG1onr+Nsp9aFSMM9kLXSnOPjPvMEgmkmJSJrZpgjiSsAsXtGY9ASBpq/RzMDNqU7ECPYE9MtNkKCxFnSN/8MW9CCIrZ7LkrdLQXk9srmOUQeCQMZcwCo2lmLRv4y25vCOz8i4qkNhQhP4Eq55xF83misRuYAd4ecMvEEi0LU+ykiO9eCun62pLWLN3kT5dJ6MZ4wd61c9DtLGx6ZeyjfaxNZN/6Cm1QnCzMPQFJAxyFhGcCBqwXUKuQXEUKnWHN+7qA1fNfgvGwia9owUzs9HuO+vjY8fKFYNNIrXKcBq38BLtjSp2zxup3Nr3tDhH6iWxXYH8bVS8e22X40/AVA+r6YzW1pYEyiucq3O3CRI+xy4+GExNh4tqaVXAmxCuonvNSAT1TIx/2Kw9+8tfCxl7vB5R1u3qatrIYmQF2umEYf9/fiT7UCAoY7tvDfdKExnMX/NcsBLHNvrecphUoHLixJLfwN1AEEBHE49/6XaUWCe2ADd9oTJGxnC+ipZiPEdwvVfmjQVBHsspM7E/sGQnM6AEhMm44XBaizVQLreILblD09o9JFiKUE7w1fIhGNy/zZ62+x3dK2EkOjIXJY+6seLM7oUY+E48xuglp0rBMFTgy/nPfGHV9do=
```

The help text has also been cleaned up a bit, it now looks like this

```
Cape Encrypt

Encrypt local data for use with cape functions.

Retrieves a user-specific public key and encrypts local data so that it may be
safely shared and used as input to cape functions. Results are output to stdout
so you can easily pipe them elsewhere.

By default, cape encrypt will use your public key to encrypt data.
You can specify another user with --username.

Usage:
  cape encrypt (<input data> | -f <input file>) [flags]

Examples:
  cape encrypt "foo"                       Encrypt a string
  echo '1234' | cape encrypt               Encrypt input data read from stdin
  cape encrypt -f example.txt              Encrypt data read from a file named "example.txt"
  cape encrypt hello --username capedocs   Encrypt using capedocs publickey

Flags:
  -f, --file string       input data file (or '-f -' to accept stdin)
  -h, --help              help for encrypt
      --username string   username of the key owner

Global Flags:
  -c, --config string   config file (default "$HOME/.config/cape/presets.json")
  -o, --output string   output format (default "plain")
  -v, --verbose         verbose output
```