use protocol class from sentinel for deploy (#106)
Example of output when we see an error. In this example, I deleted the AWS creds on supervisor, so that the deploy call would fail.

```
$ cape deploy isprime --url $WSS_URL --insecure
Deploying function to Cape ...

Error: unable to deploy function: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Goes with https://github.com/capeprivacy/sentinel/pull/113